#### 3-11

In [3]:
## dependencies
import numpy as np

## Data; Yearly salary in($1000) [2025,2026,2027]
dataScientist = [130,132,137]
productManager = [127,140,145]
designer = [118,118,127]
softwareEngineer = [129,131,137]

employees = np.array([
    dataScientist,
    productManager,
    designer,
    softwareEngineer
])

In [4]:
## one liner
employees[0,::2] = employees[0,::2] * 1.1

In [5]:
## result
print(employees)

[[143 132 150]
 [127 140 145]
 [118 118 127]
 [129 131 137]]
